name: todo_craft_3d
description: A responsive 3D Todo app built with Flutter, Firebase and MVVM.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  firebase_core: ^4.15.0
  cloud_firestore: ^6.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#6C4DF6"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  min_sdk_android: 21