// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCgFHTcEMd46EAalwBa35LxceoIB1sYhE',
    appId: '1:309508665098:web:5a1e18aabdbe5847d394f3',
    messagingSenderId: '309508665098',
    projectId: 'todo-craft-3d',
    authDomain: 'todo-craft-3d.firebaseapp.com',
    storageBucket: 'todo-craft-3d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0CfXFIBRNgnY0cW3kQHduqa8ZU6iiicg',
    appId: '1:309508665098:android:47ef2ff4ef6af911d394f3',
    messagingSenderId: '309508665098',
    projectId: 'todo-craft-3d',
    storageBucket: 'todo-craft-3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP5XIHcyoi6qPO7LEL6Rjz5SE7QE4kww4',
    appId: '1:309508665098:ios:8af254ac79719000d394f3',
    messagingSenderId: '309508665098',
    projectId: 'todo-craft-3d',
    storageBucket: 'todo-craft-3d.firebasestorage.app',
    iosBundleId: 'com.example.todoCraft3d',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP5XIHcyoi6qPO7LEL6Rjz5SE7QE4kww4',
    appId: '1:309508665098:ios:8af254ac79719000d394f3',
    messagingSenderId: '309508665098',
    projectId: 'todo-craft-3d',
    storageBucket: 'todo-craft-3d.firebasestorage.app',
    iosBundleId: 'com.example.todoCraft3d',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCgFHTcEMd46EAalwBa35LxceoIB1sYhE',
    appId: '1:309508665098:web:ed1f672834f16ec7d394f3',
    messagingSenderId: '309508665098',
    projectId: 'todo-craft-3d',
    authDomain: 'todo-craft-3d.firebaseapp.com',
    storageBucket: 'todo-craft-3d.firebasestorage.app',
  );
}
